name: analyse

on: [push]

jobs:
  analysis-rhel-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Free space
        run: df -h
      - name: Delete unused software
        # This is necessary for running CScope database build as it takes
        # a lot of disk space and the runners die silently when out of space.
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
      - name: Free space
        run: df -h
      - name: Prepare Build Environment
        run: |
          mkdir -p ${{ github.workspace }}/build

      - name: Configure and Build
        run: >
          nix develop . --command bash -c
          "cmake -B build ${{ github.workspace }} -GNinja -DCMAKE_BUILD_TYPE=Release &&
           ninja -C build"
      - name: Run analysis
        shell: bash
        run: >
          nix develop . --command bash -c 'setuptoolsShellHook && bash .github/workflows/analysis-rhel-functions.sh ./bin/diffkemp'
  analysis-rhel-sysctls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Free space
        run: df -h
      - name: Delete unused software
        # This is necessary for running CScope database build as it takes
        # a lot of disk space and the runners die silently when out of space.
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
      - name: Free space
        run: df -h
      - name: Prepare Build Environment
        run: |
          mkdir -p ${{ github.workspace }}/build

      - name: Configure and Build
        run: >
          nix develop . --command bash -c
          "cmake -B build ${{ github.workspace }} -GNinja -DCMAKE_BUILD_TYPE=Release &&
           ninja -C build"
      - name: Run analysis
        shell: bash
        run: >
          nix develop . --command bash -c 'setuptoolsShellHook && bash .github/workflows/analysis-rhel-sysctls.sh ./bin/diffkemp'
